### ISSUE TITLE
Title display

### ISSUE THREAD

**Issue by bibideve** [Geospace/ghb#2]
In the roms like "pokemon emeraude (French Version)" the title is not well displaying, it shows unreadable characters.
Same as if i send him /dev/urandom, it works (he should not ?) and show and random title with unreadble characters.

**Comment by lucas-santoni** [comment]
Thanks for the report.

Pokemon Emeraude is a GBA ROM which uses a different header, this is why you see strange things. I fixed this in the [tables](/Geospace/ghb/tree/tables) branch with a force option.

`/dev/urandom` is a special file, which outputs an error in the [tables](/Geospace/ghb/tree/tables) branch.

Will keep you updated as I merge.

**Comment by lucas-santoni** [comment]
Fixed by #3 ! :)
